// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID        string
	Timestamp sql.NullTime
	ToolName  string
	Operation string
	Actor     string
	TargetID  sql.NullString
	InputHash sql.NullString
	Result    string
	Details   sql.NullString
	ContextID string
}

type Characteristic struct {
	ID        string
	HolonID   string
	Name      string
	Scale     string
	Value     string
	Unit      sql.NullString
	CreatedAt sql.NullTime
}

type Evidence struct {
	ID             string
	HolonID        string
	Type           string
	Content        string
	Verdict        string
	AssuranceLevel sql.NullString
	CarrierRef     sql.NullString
	ValidUntil     sql.NullTime
	CreatedAt      sql.NullTime
}

type Holon struct {
	ID           string
	Type         string
	Kind         sql.NullString
	Layer        string
	Title        string
	Content      string
	ContextID    string
	Scope        sql.NullString
	ParentID     sql.NullString
	CachedRScore sql.NullFloat64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Relation struct {
	SourceID        string
	TargetID        string
	RelationType    string
	CongruenceLevel sql.NullInt64
	CreatedAt       sql.NullTime
}

type Waiver struct {
	ID          string
	EvidenceID  string
	WaivedBy    string
	WaivedUntil time.Time
	Rationale   string
	CreatedAt   sql.NullTime
}

type WorkRecord struct {
	ID             string
	MethodRef      string
	PerformerRef   string
	StartedAt      time.Time
	EndedAt        sql.NullTime
	ResourceLedger sql.NullString
	CreatedAt      sql.NullTime
}
